export const CONFIG_SERVICE = 'CONFIG_SERVICE'

export const DBL_SERVICE = 'DBL_SERVICE'

export const BOOKS_REPOSITORY = 'BOOKS_REPOSITORY'
export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY'
export const STORAGES_REPOSITORY = 'STORAGES_REPOSITORY'

export const REFRESH_TOKENS_REPOSITORY = 'REFRESH_TOKENS_REPOSITORY'
export const USER_ROLES_REPOSITORY = 'USER_ROLES_REPOSITORY'
export const USER_REPOSITORY = 'USER_REPOSITORY'
